### ISSUE TITLE
Multiple frontends

### ISSUE THREAD

**Issue by hansbogert** [geerlingguy/ansible-role-haproxy#3]
Is it possible to have multiple frontends?
In my case I need to have port 80 for non-ssl and 443 for ssl requests.

**Comment by amnay-mo** [comment]
I would great to have:
1. multiple frontends
2. multiple backends
3. ACLs for reverse-proxying
4. LB on each backend's cluster

**Comment by geerlingguy** [comment]
To be honest, I'm currently not using HAProxy for any live infra (just for testing), as I'm sticking with Nginx and Varnish for most of my needs, so I probably won't get around to adding this support too soon. But if someone wants to take a crack at doing it (probably doing one thing per PR, instead of tossing a 100+ line change PR my way), I would be willing to test and merge.

**Comment by joshmoore** [comment]
NB: https://github.com/openmicroscopy/ansible-role-haproxy/commit/d3e3c5df4ee27506439e7bd92526bc013ead9c35 is an attempt at this.
