### ISSUE TITLE
Manage haproxy config with personal template

### ISSUE THREAD

**Issue by mabed-fr** [geerlingguy/ansible-role-haproxy#36]
Hello, I want to manager personal template with haproxy.

This is my work
`
- name: Copy HAProxy configuration in place.
  template:
    src: "{{ haproxy_template | default('haproxy.cfg.j2') }}"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy
`
I change "SRC"

i have tested with this groupvars:
```

cat group_vars/lbservers 
---

# HA PROXY #
haproxy_template: "../../../files/haproxy/haproxy.cfg.j2"
```
It's work fine :

Regards,

Mathieu

**Comment by rutger1140** [comment]
This is exactly what I have been looking for, since I wanted to enable the build-in stats endpoint.

Right now I run an entire copy of the role in my project just for this addition to the `haproxy.cfg.j2`:
```yaml
listen stats
    bind :8404
    mode http
    stats enable
    stats hide-version
    stats refresh 10s
    stats uri /
    stats auth {{ haproxy_stats_username }}:{{ haproxy_stats_password }}
```

Maybe this could be added to the role?

---

**Update:**
I ended up using the [ansible-haproxy role from Oefenweb](https://github.com/Oefenweb/ansible-haproxy), which is more complete and maintained.
